### ISSUE TITLE
DnrTv episode link no longer exists (404)

### ISSUE THREAD

**Issue by clrockwell** [AutoMapper/AutoMapper.website#7]
Hey - new to AutoMapper so just poking around and noticed the link was broken.  Via the waybackmachine I found the .wmv file: http://s3.amazonaws.com/dnrtv/dnrTV_0155.wmv.

I'm not sure how relevant it is since it was recorded in 2009 but if it still is maybe it can be uploaded to youtube or similar and the link updated?

Thanks!

**Comment by lbargaoanu** [comment]
Fixed by #8.

**Comment by PalashBansal** [comment]
> Hey - new to AutoMapper so just poking around and noticed the link was broken. Via the waybackmachine I found the .wmv file: http://s3.amazonaws.com/dnrtv/dnrTV_0155.wmv.
> 
> I'm not sure how relevant it is since it was recorded in 2009 but if it still is maybe it can be uploaded to youtube or similar and the link updated?
> 
> Thanks!

how about https://youtu.be/dh9jpB-en5Q ?

**Comment by lbargaoanu** [comment]
I'm not impressed :) Anyway, people can find stuff by themselves.
